### PR TITLE
Improvement of build setup mainly no confusing src directory.

### PR DESCRIPTION
**Pull request by bhalonen**
Small improvement over before.

### CODE REVIEW

**Comment by markhalonen** [comment]
I'm not sure what's going on. I just re-cloned and ran the build commands from master. Where does this install? I do not see it in my Applications folder as I expect. I may have fooled myself earlier, as I use SpotLight to find apps, but it just finds the SurePulse.app located in the `build` folder. So I'm not sure what's going on. @bhalonen does yours install to Applications?

**Comment by bhalonen** [comment]
This makes an installer that goes in ```build/jfx/native``` I'll add that to the README.md

**Comment by markhalonen** [comment]
just tested again, unable to confirm it installs to the Applications folder on Mac

**Comment by markhalonen** [comment]
Also where is the windows installer? Can we add that to the readme?

**Comment by bhalonen** [comment]
Same path I think. They just go next to each other.

**Comment by bhalonen** [comment]
I got it to work, repeatably. I deleted the app right next to the one I was using, that seemed to make it work.
I think it only breaks for developers.

**Comment by markhalonen** [comment]
Getting this error on windows:
image

I used the `gradlew.bat` script, so from powershell I did `gradlew.bat build` then `gradlew.bat jN`. We should update the README with instructions for Windows

**Comment by markhalonen** [comment]
ah, was able to see it work on Mac. Deleted the app from the native folder and copied the `pkg` to downloads (realistic user scenario) and now it's in my Applications 🎉

**Comment by markhalonen** [comment]
So it's looking good for Mac, but not for Windows. I never tested this new build system on Windows, so really I should have done this on the original build PR.

**Comment by markhalonen** [comment]
Able to install on Windows :+1:

**Pull request merged**
