### PR TITLE
Cherry pick shear strain correction

### PR DESCRIPTION
**Pull request by bhalonen**
I have no clue why the removal of the old icons are in this pull request.

### CODE REVIEW

**Comment by markhalonen** [comment]
ncorr changes located at https://github.com/relinc/ncorr_cpp/pull/2

**Comment by bhalonen** [comment]
Here is some example data.
https://drive.google.com/open?id=0B2ZNW4N-_jhSa2RnalBrcVVLMlhldklscU1WSDlHUUpjLVQ0

**Comment by bhalonen** [comment]
better data. https://drive.google.com/open?id=146OZvOCuBEa8FQClZzzGARZj8tcIWaPQ

**Comment by markhalonen** [comment]
Trying to test this. I can see in https://drive.google.com/open?id=146OZvOCuBEa8FQClZzzGARZj8tcIWaPQ that there are samples with DIC images, but it appears we don't save original images in the sample file? 
image

So I think that I need the original images so I can test this.

**Comment by markhalonen** [comment]
We are direly in need of a QA test plan. Something like my tutorial videos, where all the necessary info is available. We have no baseline for testing if this PR changes our DIC strain output by 10%. It would just go unnoticed.

**Pull request merged**
