### PR TITLE
Auto select fix

### PR DESCRIPTION
**Pull request by bhalonen**
Fixes auto select issues due to the wrong wave speed for a torsion sample.

### CODE REVIEW

**Comment by markhalonen** [comment]
Yes, it best to keep branching from master unless they are dependent PR's. In that case, this PR would be towards the build PR.

**Comment by markhalonen** [comment]
What kind of test should I run? I'm getting this error:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at net.relinc.processor.controllers.TrimDataController.setReflectedBeginFromIncidentAndBarSetup(TrimDataController.java:1054)
	at net.relinc.processor.controllers.TrimDataController.access$500(TrimDataController.java:74)
	at net.relinc.processor.controllers.TrimDataController$12.handle(TrimDataController.java:309)
	at net.relinc.processor.controllers.TrimDataController$12.handle(TrimDataController.java:306)
```
Dunno if I have the right bar setup and everything

**Comment by bhalonen** [comment]
My constraint on the branching: I need to ship something tomorrow, so not having a "tip" to deploy tomorrow would be bad.

**Comment by bhalonen** [comment]
Unfortunately army bases don't have internet.

**Pull request closed without merging**
